In [3]:
import  numpy as np

In [9]:
np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#np.linspace(시작하는숫자, 끝나는숫자, 개수)- 등rksrurdmfh wofytodtjd

In [5]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [11]:
x=np.array([
    [1,2],
    [3,4]
])
y=np.array([
    [5,6],
    [7,8]
])

In [12]:
print(x,y)
print(np.dot(x,y))

[[1 2]
 [3 4]] [[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [13]:
print(np.sqrt(x))
print(np.matmul(x,y))


[[1.         1.41421356]
 [1.73205081 2.        ]]
[[19 22]
 [43 50]]


In [14]:
array=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [43]:
arr2D=array

In [19]:
array[0]
array[0,0]
array[-1]
array[-1,-1]

9

In [21]:
arrID=np.array([1,2,3,4])
arrID

array([1, 2, 3, 4])

In [22]:
array > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [23]:
array[array > 5]

array([6, 7, 8, 9])

In [24]:
array[array %2==0]

array([2, 4, 6, 8])

In [25]:
print(arrID>2)

[False False  True  True]


In [26]:
print( arrID>2)

[False False  True  True]


In [27]:
arrID[False,False,True,True]

array([], shape=(0, 4), dtype=int64)

In [33]:
array[0,:]
array[:,1]
array[:2,1:]
array[-1:,1:3]

array([[8, 9]])

In [35]:
np.reshape(array,9)
np.reshape(array,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
array.sum()
array.sum(axis=1)
array.sum(axis=0)
#0이면 열기준 1이면 행기준

array([12, 15, 18])

In [44]:
arr2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [48]:
np.save('/content/drive/MyDrive/SSW2_2022/array',array)
#구글 드라이브에 저장하고 싶은 폴더의 경로를 복사

In [49]:
array_test = np.load('/content/drive/MyDrive/SSW2_2022/array.npy')
#구글 드라이브에서 읽어오고 싶은 파일의 경로를 복사

In [51]:
import pandas as pd

In [55]:
series = pd.Series([1,2,3])
series

0    1
1    2
2    3
dtype: int64

In [53]:
series = pd.Series([11,2,3], index=['A','B','C'])
series

A    11
B     2
C     3
dtype: int64

In [58]:
dataframe = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
dataframe

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [59]:
dataframe = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],
                         index=['A','B','C'],columns=['X1','X2','X3'])
dataframe

X1  X2  X3
A   1   2   3
B   4   5   6
C   7   8   9

In [61]:
dataframe.index

Index(['A', 'B', 'C'], dtype='object')

In [64]:
dataframe.columns

Index(['X1', 'X2', 'X3'], dtype='object')

In [65]:
dataframe.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
dataframe.T

A  B  C
X1  1  4  7
X2  2  5  8
X3  3  6  9

In [67]:
dataframe.head(1)


X1  X2  X3
A   1   2   3

In [69]:
df=dataframe

In [70]:
df

X1  X2  X3
A   1   2   3
B   4   5   6
C   7   8   9

In [71]:
df.tail(1)

X1  X2  X3
C   7   8   9

In [72]:
df.describe()

X1   X2   X3
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [76]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, A to C
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X1      3 non-null      int64
 1   X2      3 non-null      int64
 2   X3      3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes


In [84]:
dataframe

X1  X2  X3
A   1   2   3
B   4   5   6
C   7   8   9

In [78]:
dataframe.sort_index(ascending=False, axis=1)

X3  X2  X1
A   3   2   1
B   6   5   4
C   9   8   7

In [89]:
dataframe.sort_values('X1',ascending=False)

X1  X2  X3
C   7   8   9
B   4   5   6
A   1   2   3

In [83]:
dataframe.sort_values(['X1','X3'], ascending=[False,True])

X1  X2  X3
C   7   8   9
B   4   5   6
A   1   2   3

In [90]:
dataframe[:2]

X1  X2  X3
A   1   2   3
B   4   5   6

In [91]:
dataframe.loc['A','X1']

1

In [92]:
dataframe.loc['A','X1':]

X1    1
X2    2
X3    3
Name: A, dtype: int64

In [93]:
dataframe.loc['A',['X1','X3']]

X1    1
X3    3
Name: A, dtype: int64

In [95]:
dataframe.loc['A':,['X1','X3']]

X1  X3
A   1   3
B   4   6
C   7   9

In [105]:
from sklearn.datasets import load_iris
iris.data = load_iris()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  


In [120]:
iris = pd.DataFrame(data=iris.data, columns=iris.feature_names)

AttributeError: ignored

In [119]:
iris_head()

NameError: ignored