In [ ]:
import numpy as np

In [ ]:
list1= [1,2,3,4]

In [ ]:
arr1 = np.array(list1)

In [ ]:
 print(arr1)

[1 2 3 4]


In [ ]:
print(arr1.shape)

(4,)


In [ ]:
list2= [5,6,7,8]
arr2= np.array([list1, list2])

In [ ]:
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(arr2.shape)

(2, 4)


In [ ]:
list3=[1,2,3,4,5,6,7,8]

In [ ]:
arr3 = np.array(list3).reshape(4,2)
print(arr3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
m = np.array(range(20)).reshape(5,4)
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [ ]:
m[:,1]

array([ 1,  5,  9, 13, 17])

In [ ]:
m2=m[0:3, :3]
bool = np.array([[True, False, False],
                 [False, False, True],
                 [False, True, True]])
m2[bool]

array([ 0,  6,  9, 10])

In [ ]:
m2 >= 3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
m2 % 1 == 0

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [77]:
#np.array 행렬로 만들어줌줌
# np.array().reshpae(행,열 설정) print(a.shape)행열 보여줌
#a+b
np.add(a,b)
#b-a
np.subtract(b,a)
#a*b
np.multiply(a,b)
#a/b
np.divide(a,b)
#행렬끼리 곱
np.dot(a ,b)
#전체 합계
np.sum(m3)
#열끼리의 합
np.sum(m3, axis=0)
#행끼리의 합
np.sum(m3, axis=1)

array([30, 42, 54])

In [ ]:
a= np.array([2,6,8])
b= np.array([1,7,10])

In [ ]:
print(m2)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


In [74]:
m3 = m[2:, 1:]
print(m3)

[[ 9 10 11]
 [13 14 15]
 [17 18 19]]


In [ ]:
np.add(m2, m3)

array([[ 9, 11, 13],
       [17, 19, 21],
       [25, 27, 29]])

In [ ]:
np.dot(m2, m3) #0*9 + 1*13 2*17

array([[ 47,  50,  53],
       [203, 218, 233],
       [359, 386, 413]])

In [ ]:
np.sum(m3)

126

In [ ]:
menu = ['', 'Americano','Latte','Espresso','Mocha','식혜','수정과']
price = [0,1500,2000,1700,2500,2000,1900]


for i in range(1,7):
  print(i, menu[i], price[i])

1 Americano 1500
2 Latte 2000
3 Espresso 1700
4 Mocha 2500
5 식혜 2000
6 수정과 1900


In [ ]:
a = [1,1,1,1,1,2,2,2,2,3,3,3,3,4,5]
b = set(a)
print(b)
c = list(b)
print(c)

{1, 2, 3, 4, 5}
[1, 2, 3, 4, 5]


In [ ]:
a = b= [1,2,3]
a[1]= 4
print(b)

[1, 4, 3]


In [ ]:
a=(1,2,3)
a = a - ()

TypeError: ignored